package com.cg.framework.constant;

/**
 * Spring constant is used to declare all the constant which are used for Spring related configuration parameters.
 * 
 * @author anangupt
 *
 */
public enum EnvConstant {

    CACHE_SERVICE_ENDPOINT("CACHE_SERVICE_ENDPOINT"),
	CACHE_SERVICE_PORT("CACHE_SERVICE_PORT"),
	OKTA_INTERNAL_ISSUER_URL("OKTA_INTERNAL_ISSUER_URL"),
	OKTA_INTERNAL_CLIENT_ID("OKTA_INTERNAL_CLIENT_ID"),
	OKTA_ISSUER_URL("OKTA_ISSUER_URL"),
	OKTA_CLIENT_ID("OKTA_CLIENT_ID"),
	AWS_RDS_DBURL("AWS_RDS_DBURL"),
	AWS_RDS_USER_NAME("AWS_RDS_USER_NAME"),
	AWS_RDS_SCHEMA("AWS_RDS_SCHEMA"),
	AWS_RDS_PASSWORD("AWS_RDS_PASSWORD"),
	COSMOS_API_END_POINT("COSMOS_API_END_POINT"),
	COSMOS_API_PORT("COSMOS_API_PORT"),
	DEALER_SEARCH_URI("DEALER_SEARCH_URI"),
	DEMOGRAPHIC_INFO_URI("DEMOGRAPHIC_INFO_URI"),
	FREQUENTS_DEALERS_URI("FREQUENTS_DEALERS_URI"),
	DEALER_PAYMENT_STATUS_URI("DEALER_PAYMENT_STATUS_URI"),
	SUBMIT_FLOORPLAN("SUBMIT_FLOORPLAN"),
	VEHICLE_COLOR_URI("VEHICLE_COLOR_URI"),
	PAYMENT_STATUS("PAYMENT_STATUS"),
	PAYMENT_DETAILS("PAYMENT_DETAILS"),
	VEHICLE_DETAILS("VEHICLE_DETAILS"),
	EXPORT_PAYMENT_STATUS("EXPORT_PAYMENT_STATUS"),
	VIEW_FLOORPLAN_REQUESTS("VIEW_FLOORPLAN_REQUESTS"),
	FLOORPLAN_REQUEST_VEHICLE_INFO("FLOORPLAN_REQUEST_VEHICLE_INFO"),	
	EXPORT_FLOORPLAN_REQUESTS("EXPORT_FLOORPLAN_REQUESTS"),
	PAYMENT_STATUS_SEARCH_FILTER_RESULT("PAYMENT_STATUS_SEARCH_FILTER_RESULT"),
	OKTA_SSWS("OKTA_SSWS"),
	OKTA_USER_CREATE("OKTA_USER_CREATE"),
	OKTA_GROUP_NAME("OKTA_GROUP_NAME"),
	OKTA_BASE_URL("OKTA_BASE_URL"),
	OKTA_CALLBACK("OKTA_CALLBACK"),
	SESSION_TIME_OUT("SESSION_TIME_OUT"),
	AUCTION_START_DATE_FOR_INTERNAL_USER("AUCTION_START_DATE_FOR_INTERNAL_USER"),
	FLOOR_PLAN_DAYS_FOR_INTERNAL_USER("FLOOR_PLAN_DAYS_FOR_INTERNAL_USER"),
	DEFAULT_MAX_SEARCH_RESULTS_FOR_INTERNAL_USER("DEFAULT_MAX_SEARCH_RESULTS_FOR_INTERNAL_USER"),
	SENTRY_DSN("SENTRY_DSN"),
	SENTRY_EMAIL("SENTRY_EMAIL"),
	BUILD_ID("BUILD_ID"),
	ENABLED_SENTRY("ENABLED_SENTRY");
	
	
	/**Hold the constant property.
	 * 
	 */
	private String val;

	EnvConstant(String val){
		this.val = val;
	}
	
	public String getVal() {
		return System.getenv(this.val);
	}
	
}
